= Cookie Cutter Template: Command-Line-Interface Filter (Python)

[width=100%,cols=2,5]
|===
|Project site    | https://github.com/polyglot-jones/cookiecutter-cli-filter
|Issues          | https://github.com/polyglot-jones/cookiecutter-cli-filter/issues/
|Authors         | Craig Jones (polyglot-jones)
|Latest Version  | 0.0.1
|Python versions | 3.6 or above
|===

This project is a link:https://github.com/cookiecutter/cookiecutter[cookiecutter] template. 
This template generates a skeleton Python app -- specifically, an app that's meant to be invoked via the command line.
The "`filter`" part refers to a program that accepts input via stdin, processes it in some way, and then sends that processed data along to stdout. (And all non-data logging information is streamed to stderr.)
But, that's just a suggestion. 
You can certainly have your command-line tool work any way you want.

== Features and Characteristics of this Template

*Project Structure:*

(In all of the following, `myapp` will be replaced with whatever name (slug) you give your tool.)

The root folder is `/myapp`. Within that are these files and subfolders:

* myapp/ -- The source code. (So, that's /myapp/myapp/... in case that's not clear.)
* myapp/logic/ -- The "`business logic`" code that actually performs the task at hand. This code is of great concern to whoever is wearing the subject-matter hat.
* myapp/core/ -- "`Infrastructure code`" that supports the business logic. This code is of more concern to whoever is wearing the operations hat. This code knows a little bit about the task at hand, but doesn't get deep into the details.
* myapp/util/ -- "`Utility code`" that has nothing to do with the task at hand, per se. (Consider this an incubator for code that might someday be extracted into a separate module for use by other apps.)
* myapp/#__main__#.py -- The main body of the app. It parses the command line, loads the configuration (if any), sets up the logging, invokes your business logic, and then handles otherwise uncaught exceptions.
* doc/ -- The user docs for your tool.
* doc_technical/ -- Documentation aimed at yourself and possible collaborators.
* tests/ -- The unit tests.
* setup.py -- The beginnings of a setup.py (in case your app grows into a module worthy of submitting to PyPl).
* requirements.txt -- Names the external Python modules that your app requires (just `colorlog` to start).


*Unit Testing:* 

* A few initial unit tests are provided. They use `PyTest` (but that's easily changed).

*Logging:* 

* The standard Python `logging` mechanism is customized with two additional logging levels: DIAGNOSTIC and TRACE.
Thus, it goes: critical, error, warning, info, DIAGNOSTIC, debug, TRACE. 

* Two versions of the log are created. 
A detailed log is written to disk. 
A less noisy log is sent to the console (to `stderr` to be precise).

* The version of the log that is saved to disk always includes all log messages at every level.

* The default name of this log file is myapp.log (where myapp is the name (slug) for the tool being created.) 
Use the `--filename` switch to specify a different name. 
Use the `--nologfile` switch to suppress it altogether.

* By default the version of the log written to the console (stderr) excludes DIAGNOSTIC, DEBUG and TRACE. 
Use the `--verbose`, `--debug`, or `--trace` switches to set the console logging level to DIAGNOSTIC, DEBUG, or TRACE, respectively.

* Log messages sent to the console are colorized (via `colorlog`) by default. 
(The --nocolor switch turns this off.) 

*Command Line Switches:* 

* The command line arguments are handled via the `argparse` module. This template includes a number of argument definitions to start:
* `--help` (or `-h`) and `--version` are handled directly by `argparse`.
* `--verbose` (or `-v`), `--debug`, `--trace`, `--logfile` (or `-l`), `--nologfile`, and `--nocolor` affect the logging (as described above).
* `--devel` (or `-d`) is intended to turn on "`dev mode.`" Use this however you like.
* `--infile` (or `-i`) allows you to specify the name (and path) for the input (instead of stdin).
* `--outfile` (or `-i`) allows you to specify the name (and path) for the output (instead of stdout).

*Configuration and Settings:*

* Configuration is handled via `configparser` (INI format).
* This template distinguishes between "`configurations`" and "`settings.`" Configuration options are read-only. (The user must edit the INI file manually.) 
* On the other hand, settings are read/write. (The app uses "`settings`" to save state between sessions.) Note: Filter tools rarely need to save state between sessions, so feel free to rip that part out, but just in case you are using this template as the basis for some other kind of tool, it's there if you need it.

*Exception Handling:*

* There are a few custom Exception classes defined (e.g. MyAppConfigError), to get you started.
* Each of these custom exceptions have an associated `exitcode` attribute. Any uncaught exception that makes it all the way back to main will cause the app to exit out. If the exception has an `exitcode` attribute, then that's the code that will be passed back to the operating system. Otherwise, it will return 1. (0 is a normal exit.)
* Before exiting, the uncaught exception is automatically logged. If the exception has a `loglevel` attribute, then that's the level at which the exception is logged (ERROR, WARNING, etc.) Otherwise, it will be logged as CRITICAL.

*Documentation:*

* Some initial documentation is generated using the GitHub flavor of AsciiDoc markup. 
* If, for some strange reason you prefer MarkDown, the docs are easily changed, of course.

*This template makes use of f-strings. Thus, it assumes Python 3.6 or above.*


== Usage

[source,bash]
----
pip install cookiecutter
cd (the parent folder where your new project will live)
cookiecutter gh:polyglot-jones/cookiecutter-cli-filter
----
Then, fill in the required information, as prompted...

[width=100%]
|===
| tool_name            | A name for your tool in title-case (e.g. Journal Sorter)
| tool_name_slug       | Base folder name for the project (keep it short, <= 12 chars suggested)
| brief_description    | A one-sentence description
| long_description     | A slightly more detailed description, if you want
| github_user          | Your GitHub user id
| github_repo          | What you'll name the repository for this project if/when you upload it to GitHub
| author               | Your full name (Title Case with spaces suggested)
| author_mail          | Your contact e-mail
| project_site         | The full URL to (what could be) the repository
| project_version      | 0.0.1
| tool_name_camel_case | For when the project name is needed as part of a CamelCase identifier (e.g. MyAppConfigError).
| year                 | For the copyright statement.
|===

Next time, you can leave out the gh:... qualifier and run the cookiecutter from your local cache:

[source,bash]
----
cookiecutter cookiecutter-cli-filter
----
Again, fill in the required information, as prompted, or...

For a do-over using the same information you entered last time:

[source,bash]
----
cookiecutter --replay cookiecutter-cli-filter
----

Note: Those answers are kept in a json file in ~/.cookiecutter_replay. Feel free to edit it first.

